server.port: 8081

feign.hystrix.enabled: true

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure.include: "*"
      base-path: /actuator
      cors.allowed-origins: true
    jmx:
      exposure.include: "*"